ShadowTracker/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ShadowTracker.Models
{
    public class Ticket //This is a data class as it stores values in the db
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Title")]
        public string Title { get; set; }

        [Required]
        [StringLength(2500)]
        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Created")]
        [DataType(DataType.Date)]
        public DateTimeOffset Created { get; set; }

        [DisplayName("Updated")]
        [DataType(DataType.Date)]
        public DateTimeOffset? Updated { get; set; }

        [DisplayName("Archival Status")]
        public bool Archived { get; set; }

        [DisplayName("Archived By Project")]
        public bool ArchivedByProject { get; set; }

        [DisplayName("Project")]
        public int ProjectId { get; set; }

        [DisplayName("Ticket Type")]
        public int TicketTypeId { get; set; }

        [DisplayName("Ticket Status")]
        public int TicketStatusId { get; set; }

        [DisplayName("Ticket Priority")]
        public int TicketPriorityId { get; set; }

        [DisplayName("Ticket Owner")]
        public string OwnerUserId { get; set; }

        [DisplayName("Ticket Developer")]
        public string DeveloperUserId { get; set; }


        //Navigational Properties
        //Parents
        public virtual Project Project { get; set; }

        public virtual TicketType TicketType { get; set; }

        public virtual TicketStatus TicketStatus { get; set; }

        public virtual TicketPriority TicketPriority { get; set; }

        public virtual BTUser OwnerUser { get; set; }

        public virtual BTUser DeveloperUser { get; set; }

        //Children
        public virtual ICollection<TicketComment> Comments { get; set; } = new HashSet<TicketComment>();
        public virtual ICollection<TicketAttachment> Attachments { get; set; } = new HashSet<TicketAttachment>();
        public virtual ICollection<Notification> Notifications { get; set; } = new HashSet<Notification>();
        public virtual ICollection<TicketHistory> History { get; set; } = new HashSet<TicketHistory>();
        public virtual ICollection<TicketTask> Tasks { get; set; } = new HashSet<TicketTask>();

    }
}

ShadowTracker/Models/TicketType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace ShadowTracker.Models
{
    public class TicketType
    {
        public int Id { get; set; }

        [DisplayName("Type Name")]
        public string Name { get; set; }

    }
}

ShadowTracker/Models/ViewModels/AssignDeveloperViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShadowTracker.Models.ViewModels
{
    public class AssignDeveloperViewModel
    {
        public Ticket Ticket { get; set; }

        public SelectList Developers { get; set; }

        public string DeveloperId { get; set; }
    }
}

ShadowTracker/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShadowTracker.Data;
using ShadowTracker.Extensions;
using ShadowTracker.Models;
using ShadowTracker.Models.Enums;
using ShadowTracker.Models.ViewModels;
using ShadowTracker.Services.Interfaces;

namespace ShadowTracker.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly IBTTicketService _ticketService;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTLookupService _lookupService;
        private readonly IBTProjectService _projectService;
        private readonly IBTFileService _fileService;
        private readonly IBTTicketHistoryService _ticketHistoryService;
        private readonly IBTNotificationService _notificationService;

        public TicketsController(UserManager<BTUser> userManager, IBTTicketService ticketService, IBTLookupService lookupService, IBTProjectService projectService, IBTTicketHistoryService ticketHistoryService, IBTFileService fileService, IBTNotificationService notificationService)
        {
            _userManager = userManager;
            _ticketService = ticketService;
            _lookupService = lookupService;
            _projectService = projectService;
            _ticketHistoryService = ticketHistoryService;
            _fileService = fileService;
            _notificationService = notificationService;
        }

        //// GET: Tickets
        //public async Task<IActionResult> UnassignedTickets()
        //{
        //    int companyId = User.Identity.GetCompanyId().Value;

        //    List<Ticket> model = await _ticketService.GetUnassignedTicketsAsync(companyId);
        //    return View(model);
        //}

        // GET: My Tickets
        public async Task<IActionResult> MyTickets()
        {
            string userId = _userManager.GetUserId(User);
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> model = await _ticketService.GetTicketsByUserIdAsync(userId, companyId);

            return View(model);
        }

        // GET: All Tickets
        public async Task<IActionResult> AllTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> model = (await _ticketService.GetAllTicketsByCompanyAsync(companyId)).OrderByDescending(p=>p.Updated).ThenByDescending(p=>p.Created).ToList();
            return View(model);
        }

        // GET: Archived Tickets
        public async Task<IActionResult> ArchivedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> model = await _ticketService.GetArchivedTicketsAsync(companyId);
            return View(model);
        }

        //GET: Unassigned Tickets
        public async Task<IActionResult> UnassignedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> model = await _ticketService.GetUnassignedTicketsAsync(companyId);

            return View(model);
        }

        //GET: Assign Developer to Ticket
        [Authorize(Roles ="Admin,ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AssignDeveloper(int? ticketId)
        {
                if (ticketId == null)
                {
                    return NotFound();
                }    

            AssignDeveloperViewModel model = new();

            model.Ticket = await _ticketService.GetTicketByIdAsync(ticketId.Value);
            model.Developers = new SelectList(await _projectService.GetProjectMembersByRoleAsync(model.Ticket.ProjectId,nameof(BTRoles.Developer)), "Id", "FullName");

            return View(model);
        }

        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignDeveloper(AssignDeveloperViewModel model)
        {
            BTUser btUser = await _userManager.GetUserAsync(User);
            if (model.DeveloperId != null)
            {

                string userId = _userManager.GetUserId(User);
                Ticket oldTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);
                try
                {
                    await _ticketService.AssignTicketAsync(model.Ticket.Id, model.DeveloperId);
                }
                catch (Exception)
                {
                    throw;
                }


                //Add Ticket History
                Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);
                await _ticketHistoryService.AddHistoryAsync(oldTicket, newTicket, userId);

                //Add Ticket Notification
                Notification notification = new()
                {
                    TicketId = model.Ticket.Id,
                    NotificationTypeId = (await _lookupService.LookupNotificationTypeId(nameof(BTNotificationType.Ticket))).Value, 
                    Title = "Ticket Assigned",
                    Message = $"Ticket : {model.Ticket.Title}, was assigned by {btUser.FullName}",
                    SenderId = userId,
                    RecipientId = model.DeveloperId
                };


                await _notificationService.AddNotificationAsync(notification);
                await _notificationService.SendEmailNotificationAsync(notification, "Ticket Assigned");

                return RedirectToAction(nameof(Details), new { id = model.Ticket.Id });

            }

            return RedirectToAction(nameof(AssignDeveloper), new { ticketId = model.Ticket.Id });

        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);

            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public async Task<IActionResult> Create()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            if(User.IsInRole(nameof(BTRoles.Admin))) //claims principal
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompanyAsync(companyId), "Id", "Name");
            }
            else
            {
                string userId = _userManager.GetUserId(User);
                ViewData["ProjectId"] = new SelectList(await _projectService.GetUserProjectsAsync(userId), "Id", "Name");
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ProjectId,TicketTypeId,TicketPriorityId")] Ticket ticket)
        {
            string userId = _userManager.GetUserId(User);
            int companyId = User.Identity.GetCompanyId().Value;
            BTUser btUser = await _userManager.GetUserAsync(User);


            if (ModelState.IsValid)
            {
                try
                {
                    ticket.Created = DateTimeOffset.Now;
                    ticket.OwnerUserId = userId;

                    ticket.TicketStatusId = (await _ticketService.LookupTicketStatusIdAsync(nameof(BTTicketStatus.New))).Value;

                    await _ticketService.AddNewTicketAsync(ticket);

                    //Ticket History 
                    Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(ticket.Id);
                    await _ticketHistoryService.AddHistoryAsync(null, newTicket, userId);

                    //Ticket Notification
                    BTUser projectManager = await _projectService.GetProjectManagerAsync(ticket.ProjectId);

                    Notification notification = new()
                    {
                        NotificationTypeId = (await _lookupService.LookupNotificationTypeId(nameof(BTNotificationType.Ticket))).Value,
                        TicketId = ticket.Id,
                        Title = "New Ticket Added",
                        Message = $"New Ticket; {ticket.Title}, was created by {btUser.FullName}",
                        Created = DateTimeOffset.Now,
                        SenderId = userId,
                        RecipientId = projectManager?.Id
                    };


                    await _notificationService.AddNotificationAsync(notification);
                    if(projectManager != null)
                    {
                        await _notificationService.SendEmailNotificationAsync(notification, $"New Ticket Added For Project: {newTicket.Project.Name}");
                    }
                    else
                    {
                        await _notificationService.SendEmailNotificationsByRoleAsync(notification, companyId, nameof(BTRoles.Admin));
                    }


                }
                catch (Exception)
                {

                    throw;
                }
                return RedirectToAction(nameof(AllTickets));
            }

            if (User.IsInRole(nameof(BTRoles.Admin))) //claims principal
            {

ShadowTracker/Views/Tickets/AllTickets.cshtml
@model IEnumerable<ShadowTracker.Models.Ticket>

@{
    ViewData["Title"] = "All Tickets";
}

<h1>All Tickets</h1>

<table class="table-responsive table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Archived)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArchivedByProject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                Ticket Type
            </th>
            <th>
                Ticket Status
            </th>
            <th>
                Ticket Priority
            </th>
            <th>
                Developer User
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {


            @if (item.Archived == false)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Archived)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArchivedByProject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Project.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TicketType.Name)
                    </td>
                    @if (item.TicketStatus.Name == "New")
                    {
                        <td><span class="badge badge-success">@item.TicketStatus.Name </span></td>
                    }
                    else if (item.TicketStatus.Name == "Development")
                    {
                        <td><span class="badge badge-development">@item.TicketStatus.Name </span></td>
                    }
                    else
                    {
                        <td><span class="badge badge-other">@item.TicketStatus.Name </span></td>
                    }
                    @if (item.TicketPriority.Name == "Urgent")
                    {
                        <td><span class="badge badge-urgent">@item.TicketPriority.Name </span></td>

                    }
                    else
                    {
                        <td><span class="badge">@item.TicketPriority.Name </span></td>
                    }
                    <td>
                        @Html.DisplayFor(modelItem => item.DeveloperUser.FullName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                        <a asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i></a>
                        @if (item.Archived == false)
                        {
                            <a asp-action="Archive" asp-route-id="@item.Id"><i class="bi bi-archive"></i></a>

                        }
                        @if (item.Archived == true)
                        {
                            <a asp-action="Restore" asp-route-id="@item.Id"><i class="bi bi-node-plus"></i></a>
                        }

                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ShadowTracker/Views/Tickets/Archive.cshtml
@model ShadowTracker.Models.Ticket

@{
    ViewData["Title"] = "Archive";
}

<h3>Are you sure you want to archive this ticket?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ArchivedByProject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ArchivedByProject)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt class="col-sm-2">
            Ticket Type
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TicketType.Name)
        </dd>
        <dt class="col-sm-2">
            Ticket Status
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TicketStatus.Name)
        </dd>
        <dt class="col-sm-2">
            Ticket Priority
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TicketPriority.Name)
        </dd>
        <dt class="col-sm-2">
            Developer User
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DeveloperUser.FullName)
        </dd>
    </dl>

    <div class="row pt-3 gy-2">
        <form asp-action="Archive">
            <input type="hidden" asp-for="Id" />
            <a class="btn btn-outline-jhprimary" asp-action="AllTickets">Return to All Tickets</a>
            <input type="submit" value="Archive" class="btn btn-danger" />
        </form>
    </div>
</div>

ShadowTracker/Views/Tickets/ArchivedTickets.cshtml
@model IEnumerable<ShadowTracker.Models.Ticket>

@{
    ViewData["Title"] = "Archived Tickets";
}

<h1>Archived Tickets</h1>

<table class="table table-responsive table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Archived)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArchivedByProject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                Ticket Type
            </th>
            <th>
                Ticket Status
            </th>
            <th>
                Developer User
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {


            @if (item.Archived == true || item.ArchivedByProject == true)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Archived)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArchivedByProject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Project.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TicketType.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TicketStatus.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeveloperUser.FullName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                        <a asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i></a>
                        <a asp-action="Restore" asp-route-id="@item.Id"><i class="bi bi-node-plus"></i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ShadowTracker/Views/Tickets/AssignDeveloper.cshtml
@model ShadowTracker.Models.ViewModels.AssignDeveloperViewModel
@using ShadowTracker.Services.Interfaces
@using Microsoft.AspNetCore.Identity
@using ShadowTracker.Extensions;

@inject UserManager<BTUser> UserManager
@inject IBTProjectService ProjectService

@{
    ViewData["Title"] = "AssignDevelopers";
}

<div class="container-fluid ">
    <div class="row">
        <div class="column text-center col-md-4">
            <h3>Assign Developer to @Model.Ticket.Title</h3>
            <div class="card">
                <div class="card-header">
                    <label class="control-label">
                        <a style="font-size:small" asp-action="Details" asp-controller="Projects" asp-route-id="@Model.Ticket.ProjectId">Project: @Model.Ticket.Project.Name</a>
                    </label>
                </div>
                <div class="card-body">
                    <form method="post" asp-action="AssignDeveloper" asp-controller="Tickets">
                        <input asp-for="Ticket.Id" hidden />
                        <div class="form-group">
                            <label class="col-form-label">Select Developers</label>
                            <select required asp-for="DeveloperId" class="form-control" asp-items="@Model.Developers">
                                <option></option>
                            </select>
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Assign" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
        @*<div>
            <a asp-action="Details" asp-controller="Projects" asp-route-id="@Model.Ticket.ProjectId">Back to Project</a>
        </div>*@
</div>

ShadowTracker/Views/Tickets/Edit.cshtml
@model ShadowTracker.Models.Ticket
@using ShadowTracker.Models.Enums

@{
    ViewData["Title"] = "Edit";
}




<div class="container-fluid">
    <h1>Edit Ticket</h1>
    <hr />
    <div class="row">
        <div class="col">
            <form asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ProjectId" />
                <input type="hidden" asp-for="Created" />
                <input type="hidden" asp-for="OwnerUserId" />
                <input type="hidden" asp-for="DeveloperUserId" />
                <input type="hidden" asp-for="Archived" />
                <input type="hidden" asp-for="ArchivedByProject" />

                <div class="row gy-2">
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row gy-2">
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row gy-2">
                    <div class="col col-md-3">
                        <div class="form-group">
                            <label asp-for="TicketTypeId" class="control-label"></label>
                            <select asp-for="TicketTypeId" class="form-control" asp-items="ViewBag.TicketTypeId">
                                <option></option>
                            </select>
                            <span asp-validation-for="TicketTypeId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col col-md-3">
                        <div class="form-group">
                            <label asp-for="TicketPriorityId" class="control-label"></label>
                            <select asp-for="TicketPriorityId" class="form-control" asp-items="ViewBag.TicketPriorityId">
                                <option></option>
                            </select>
                            <span asp-validation-for="TicketPriorityId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col col-md-3">
                        <div class="form-group">
                            <label asp-for="TicketStatusId" class="control-label"></label>
                            <select asp-for="TicketStatusId" class="form-control" asp-items="ViewBag.TicketStatusId">
                                <option></option>
                            </select>
                            <span asp-validation-for="TicketStatusId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col col-md-3 text-center">
                        <div class="form-group">
                            <label class="control-label">Ticket Developer</label>
                            <p class=""><strong>@Model.DeveloperUser?.FullName</strong></p>
                            @if (User.IsInRole(nameof(BTRoles.Admin)) || User.IsInRole(nameof(BTRoles.ProjectManager)))
                            {
                                <a class="btn btn-outline-jhprimary" asp-action="AssignDeveloper" asp-controller="Tickets" asp-route-ticketId="@Model.Id">Assign</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="row gy-2">
                    <div style="padding-left: 1rem">
                        <div class="form-group">
                            <a class="btn btn-outline-jhprimary" asp-action="AllTickets">Return to All Tickets</a>
                            <input asp-action="Details" asp-route-id="@Model.Id" type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShadowTracker/Views/Tickets/UnassignedTickets.cshtml
@model IEnumerable<ShadowTracker.Models.Ticket>
@using ShadowTracker.Models.Enums

@{
    ViewData["Title"] = "Unassigned Tickets";
}

<h1>Unassigned Tickets</h1>

<table class="table table-responsive table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Archived)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                Ticket Type
            </th>
            <th>
                Ticket Status
            </th>
            <th>
                Ticket Priority
            </th>
            <th>
                Developer User
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Archived)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketType.Name)
            </td>
            @if (item.TicketStatus.Name == "New")
            {
                <td><span class="badge badge-success">@item.TicketStatus.Name </span></td>
            }
            else if (item.TicketStatus.Name == "Development")
            {
                <td><span class="badge badge-development">@item.TicketStatus.Name </span></td>
            }
            else
            {
                <td><span class="badge badge-other">@item.TicketStatus.Name </span></td>
            }
            @if (item.TicketPriority.Name == "Urgent")
            {
                <td><span class="badge badge-urgent">@item.TicketPriority.Name </span></td>

            }
            else
            {
                <td><span class="badge">@item.TicketPriority.Name </span></td>
            }
            <td>
                <a asp-controller="Tickets" asp-action="AssignDeveloper" asp-route-ticketId="@item.Id" class="btn btn-primary btn-sm">Assign Ticket</a>
            </td>
        </tr>
        }
    </tbody>
</table>