ShadowTracker/Models/ViewModels/ManageUserRolesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShadowTracker.Models.ViewModels
{
    public class ManageUserRolesViewModel
    {
        public BTUser BTUser { get; set; }

        public MultiSelectList Roles { get; set; }

        public List<string> SelectedRoles { get; set; }
    }
}

ShadowTracker/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShadowTracker.Models;
using ShadowTracker.Models.ViewModels;
using ShadowTracker.Services.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShadowTracker.Extensions;

namespace ShadowTracker.Controllers
{
    [Authorize(Roles = "Admin")] //You have to be authenticated AND an admin.
    public class UserRolesController : Controller
    {
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyInfoService _companyInfoService;
        private readonly UserManager<BTUser> _userManager;

        public UserRolesController(IBTRolesService rolesService,
                                    IBTCompanyInfoService companyInfoService,
                                    UserManager<BTUser> userManager)
        {
            _rolesService = rolesService;
            _companyInfoService = companyInfoService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            //Add an instance of the ViewModel as a List
            List<ManageUserRolesViewModel> model = new List<ManageUserRolesViewModel>();

            //Get CompanyId
            int companyId = User.Identity.GetCompanyId().Value;

            //Get all company users
            List<BTUser> users = await _companyInfoService.GetAllMembersAsync(companyId);

            //Loop over the users to populate the ViewModel
            // - instantiate ViewModel
            // - use _rolesService
            // - Create multi-selects
            foreach (BTUser user in users)
            {
                ManageUserRolesViewModel viewModel = new ManageUserRolesViewModel();
                viewModel.BTUser = user;
                IEnumerable<string> selected = await _rolesService.GetUserRolesAsync(user);
                viewModel.Roles = new MultiSelectList(await _rolesService.GetRolesAsync(), "Name", "Name", selected);

                model.Add(viewModel);
            }

            //Return the model to the View

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {
            int companyId = (await _userManager.GetUserAsync(User)).CompanyId;

            // Instantiate the BTUser
            BTUser btUser = (await _companyInfoService.GetAllMembersAsync(companyId)).FirstOrDefault(u => u.Id == member.BTUser.Id);

            // Get Roles for the User
            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(btUser);

            string userRole = member.SelectedRoles.FirstOrDefault();

            if (!string.IsNullOrEmpty(userRole))
            {
                //Remove User from their roles
                if (await _rolesService.RemoveUserFromRolesAsync(btUser, roles))
                {
                    //Add User to the new role
                    await _rolesService.AddUserToRoleAsync(btUser, userRole);

                }
            }
            //Navigate back to the View
            return RedirectToAction(nameof(ManageUserRoles));

        }


    }
}

ShadowTracker/Views/UserRoles/ManageUserRoles.cshtml
@model IEnumerable<ShadowTracker.Models.ViewModels.ManageUserRolesViewModel>

<div class="container-fluid">
    <div class="row" style="padding-left: 5rem;">
        @foreach (var member in Model)
        {
            <div class="card col-md-5" style="margin:2px">
                <div class="card-body">
                    <h2 class="m-t-0 h3"><b>Assign Roles to @member.BTUser.FullName</b></h2>
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user: @member.BTUser.FullName. Use the dropdown to select the roles that this user should be assigned. Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method=post>
                        <input type="hidden" asp-for="@member.BTUser.Id" /> @*Don't show it to the user but save it in the backend*@
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label asp-for="@member.Roles" class="control-label">Roles for @member.BTUser.FullName</label>
                                    <select asp-for="@member.SelectedRoles" class="control-label" asp-items="@member.Roles" multiple="multiple">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                            <hr />
                            <div class="col">
                                <div class="form-group pull-right">
                                    <input type="submit" value="Assign Roles" class="btn btn-info" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
</div>