ShadowTracker/Models/Invite.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ShadowTracker.Models
{
    public class Invite
    {
        public int Id { get; set; }

        [DisplayName("Date Sent")]
        [DataType(DataType.Date)]
        public DateTimeOffset InviteDate { get; set; }

        [DisplayName("Join Date")]
        [DataType(DataType.Date)]
        public DateTimeOffset JoinDate { get; set; }

        [DisplayName("Code")]
        public Guid CompanyToken { get; set; }

        [DisplayName("Company")]
        public int CompanyId { get; set; }

        [DisplayName("Project")]
        public int ProjectId { get; set; }

        [DisplayName("Invitor")]
        public string InvitorId { get; set; }

        [DisplayName("Invitee")]
        public string InviteeId { get; set; }

        [DisplayName("Invitee Email")]
        [DataType(DataType.EmailAddress)]
        public string InviteeEmail { get; set; }

        [DisplayName("Invitee First Name")]
        public string InviteeFirstName { get; set; }

        [DisplayName("Invitee Last Name")]
        public string InviteeLastName { get; set; }

        [DisplayName("Invite Message")]
        public string Message { get; set; }

        public bool IsValid { get; set; }

        //Navigational
        public virtual Company Company { get; set; }
        public virtual BTUser Invitor { get; set; }
        public virtual BTUser Invitee { get; set; }
        public virtual Project Project { get; set; }


    }
}

ShadowTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShadowTracker.Data;
using ShadowTracker.Extensions;
using ShadowTracker.Models;
using ShadowTracker.Models.Enums;
using ShadowTracker.Models.ViewModels;
using ShadowTracker.Services.Interfaces;

namespace ShadowTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTProjectService _projectService;
        private readonly IBTRolesService _rolesService;
        private readonly IBTLookupService _lookupService;
        private readonly IBTFileService _fileService;
        private readonly IBTNotificationService _notificationService;
        private readonly IBTTicketService _ticketService;

        public ProjectsController(UserManager<BTUser> userManager, IBTProjectService projectService, IBTRolesService rolesService, IBTLookupService lookupService, IBTFileService fileService, IBTNotificationService notificationService, IBTTicketService ticketService)
        {
            _userManager = userManager;
            _projectService = projectService;
            _rolesService = rolesService;
            _lookupService = lookupService;
            _fileService = fileService;
            _notificationService = notificationService;
            _ticketService = ticketService;
        }


        //Get: My Projects
        public async Task<IActionResult> MyProjects()
        {
            //Get Current User Id
            string userId = _userManager.GetUserId(User);

            List<Project> model = await _projectService.GetUserProjectsAsync(userId);

            return View(model);
            
        }
        
        //Get: All Projects
        public async Task<IActionResult> AllProjects()
        {
            //Get Current User Id
            int companyId = User.Identity.GetCompanyId().Value;

            List<Project> model = await _projectService.GetAllProjectsByCompanyAsync(companyId);

            return View(model);
            
        }

        //GET: Archived Projects
        public async Task<IActionResult> ArchivedProjects()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Project> model = await _projectService.GetArchivedProjectsByCompanyAsync(companyId);

            return View(model);
        }


        //GET: UnAssigned Projects
        public async Task<IActionResult> UnassignedProjects()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Project> model = await _projectService.GetUnassignedProjectsAsync(companyId);

            return View(model);
        }

        [Authorize(Roles="Admin")]
        [HttpGet]
        public async Task<IActionResult> AssignPM(int projectId)
        {
            int companyId = User.Identity.GetCompanyId().Value;

            AssignPMViewModel model = new();

            model.Project = await _projectService.GetProjectByIdAsync(projectId, companyId);
            model.PMList = new SelectList(await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager),companyId),"Id","FullName");

            return View(model);
        }

        [Authorize(Roles="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignPM(AssignPMViewModel model)
        {
            if(!string.IsNullOrEmpty(model.PMId))
            {
                await _projectService.AddProjectManagerAsync(model.PMId, model.Project.Id);
                return RedirectToAction(nameof(Details), new { id = model.Project.Id });
            }

            return RedirectToAction(nameof(AssignPM), new { projectId = model.Project.Id });
        }

        [HttpGet]
        [Authorize(Roles="Admin, ProjectManager")]
        public async Task<IActionResult> AssignMembers(int projectId)
        {
            ProjectMembersViewModel model = new();

            int companyId = User.Identity.GetCompanyId().Value;

            model.Project = await _projectService.GetProjectByIdAsync(projectId, companyId);

            List<BTUser> developers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), companyId);
            List<BTUser> submitters = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Submitter), companyId);

            List<BTUser> members = developers.Concat(submitters).ToList();

            List<string> projectMembers = model.Project.Members.Select(p => p.Id).ToList();
            model.Members = new MultiSelectList(members, "Id", "FullName", projectMembers);

            return View(model);
        }

        [Authorize(Roles="Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignMembers(ProjectMembersViewModel model)
        {
            if (model.SelectedUsers != null)
            {
                List<string> memberIds = (await _projectService.GetAllProjectMembersExceptPMAsync(model.Project.Id)).Select(p => p.Id).ToList();

                //Remove current members
                foreach (string member in memberIds)
                {
                    await _projectService.RemoveUserFromProjectAsync(member, model.Project.Id);
                }

                //Add selected members
                foreach (string member in model.SelectedUsers)
                {
                    await _projectService.AddUserToProjectAsync(member, model.Project.Id);
                }
            }

            //go to project details
            return RedirectToAction(nameof(Details), new { id = model.Project.Id });
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;

            Project project = await _projectService.GetProjectByIdAsync(id.Value, companyId);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public async Task<IActionResult> Create()
        {
            //Get Company Id
            int companyId = User.Identity.GetCompanyId().Value;

            // Add ViewModel
            AddProjectWithPMViewModel model = new();

            //Load model/SelectLists with data
            model.PMList = new SelectList(await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), companyId), "Id", "FullName");
            model.Priority = new SelectList(await _lookupService.GetProjectPrioritiesAsync(), "Id", "Name" );

            return View(model);
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddProjectWithPMViewModel model)
        {
            BTUser btUser = await _userManager.GetUserAsync(User);
            if (model != null)
            {
                int companyId = User.Identity.GetCompanyId().Value;
                try
                {
                    if(model.Project.ImageFormFile != null)
                    {
                        model.Project.FileData = await _fileService.ConvertFileToByteArrayAsync(model.Project.ImageFormFile);
                        model.Project.FileName = model.Project.ImageFormFile.FileName;
                        model.Project.FileContentType = model.Project.ImageFormFile.ContentType;
                    }
                    model.Project.CompanyId = companyId;
                    model.Project.Created = DateTimeOffset.Now;

                    await _projectService.AddNewProjectAsync(model.Project);

                    //Add PM if one was chosen
                    if (!string.IsNullOrEmpty(model.PmId))
                    {
                        await _projectService.AddProjectManagerAsync(model.PmId, model.Project.Id);
                    }

                    //Save/Send Notification
                    Notification notification = new()
                    {
                        ProjectId = model.Project.Id,
                        NotificationTypeId = (await _lookupService.LookupNotificationTypeId(nameof(BTNotificationType.Ticket))).Value,
                        Title = "Project Created",
                        Message = $"Project : {model.Project.Name}, was assigned by {btUser.FullName}",
                        SenderId = btUser.Id
                    };

                    await _notificationService.AddNotificationAsync(notification);
                    await _notificationService.SendEmailNotificationsByRoleAsync(notification, companyId, nameof(BTRoles.Admin));

                    return RedirectToAction(nameof(AllProjects));
                }
                catch (Exception)
                {

                    throw;
                }

            }

            ViewData["ProjectPriorityId"] = new SelectList(await _lookupService.GetProjectPrioritiesAsync(), "Id", "Id", model.Project.ProjectPriorityId);
            return View(model.Project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;
            //Add ViewModel instance "AddProjectWithPMViewModel"
            AddProjectWithPMViewModel model = new();

            //Get Project based on Id

ShadowTracker/Views/Invites/Create.cshtml
@model ShadowTracker.Models.Invite

@{
    ViewData["Title"] = "Create";
}


<div class="container-fluid">
    <h1>Invite New Employee</h1>
    <h4>Use this form to add a new employee to an existing project.</h4>
    <hr />
    <div class="row">
        <div class="col">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row gy-2">
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <label asp-for="ProjectId" class="control-label"></label>
                            <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                        </div>
                    </div>
                    <div class="col" style="padding-top: 2rem; height: 50%">
                        <a  class="btn btn-outline-jhprimary" asp-action="Create" asp-controller="Projects">New Project</a>
                    </div>
                </div>
                <div class="row gy-2">
                    <div class="col-12 col-md-4">
                        <div class="form-group">
                            <label asp-for="InviteeFirstName" class="control-label"></label>
                            <input asp-for="InviteeFirstName" class="form-control" />
                            <span asp-validation-for="InviteeFirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="form-group">
                            <label asp-for="InviteeLastName" class="control-label"></label>
                            <input asp-for="InviteeLastName" class="form-control" />
                            <span asp-validation-for="InviteeLastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="form-group">
                            <label asp-for="InviteeEmail" class="control-label"></label>
                            <input asp-for="InviteeEmail" class="form-control" />
                            <span asp-validation-for="InviteeEmail" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row gy-2">
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="Message" class="control-label"></label>
                            <input asp-for="Message" class="form-control" />
                            <span asp-validation-for="Message" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShadowTracker/Views/Invites/Delete.cshtml
@model ShadowTracker.Models.Invite

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invite</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JoinDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsValid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsValid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitor.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitee.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ShadowTracker/Views/Invites/Details.cshtml
@model ShadowTracker.Models.Invite

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Invite</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JoinDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsValid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsValid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitor.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitee.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ShadowTracker/Views/Invites/Edit.cshtml
@model ShadowTracker.Models.Invite

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Invite</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InviteDate" class="control-label"></label>
                <input asp-for="InviteDate" class="form-control" />
                <span asp-validation-for="InviteDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JoinDate" class="control-label"></label>
                <input asp-for="JoinDate" class="form-control" />
                <span asp-validation-for="JoinDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyToken" class="control-label"></label>
                <input asp-for="CompanyToken" class="form-control" />
                <span asp-validation-for="CompanyToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvitorId" class="control-label"></label>
                <select asp-for="InvitorId" class="form-control" asp-items="ViewBag.InvitorId"></select>
                <span asp-validation-for="InvitorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeId" class="control-label"></label>
                <select asp-for="InviteeId" class="form-control" asp-items="ViewBag.InviteeId"></select>
                <span asp-validation-for="InviteeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeEmail" class="control-label"></label>
                <input asp-for="InviteeEmail" class="form-control" />
                <span asp-validation-for="InviteeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeFirstName" class="control-label"></label>
                <input asp-for="InviteeFirstName" class="form-control" />
                <span asp-validation-for="InviteeFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeLastName" class="control-label"></label>
                <input asp-for="InviteeLastName" class="form-control" />
                <span asp-validation-for="InviteeLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsValid" /> @Html.DisplayNameFor(model => model.IsValid)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShadowTracker/Views/Invites/Index.cshtml
@model IEnumerable<ShadowTracker.Models.Invite>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InviteDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JoinDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyToken)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InviteeEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InviteeFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InviteeLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsValid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Invitor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Invitee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InviteDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JoinDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyToken)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InviteeEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InviteeFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InviteeLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsValid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invitor.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invitee.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ShadowTracker/Views/Invites/ProcessInvite.cshtml
@model ShadowTracker.Models.Invite

@{ 
    ViewData["Title"] = "Process Invite";
}

<div class="container-fluid">
    <div class="card-title mt-3 text-center">
        <h2 class="title text-uppercase font-weight-bold m-0">Invitation to join @Model.Company.Name</h2><hr />
    </div>
    <div class="row">
        <div class="col text-center">
            <div class="panel card-sign">
                <div class="header">
                    <h3>
                        <span class="clearfix title">
                            <span>Welcome @Model.InviteeFirstName @Model.InviteeLastName</span>
                        </span>
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        @Model.Invitor.FullName has invited you to collaborate on the @Model.Project.Name project.
                        <br /><br /> Click the "JOIN" button below to register with the company.
                    </p>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-3 col"><a class="btn btn-primary btn-lg btn-block" asp-area="Identity" asp-page="/Account/RegisterByInvite" asp-route-id="@Model.Id" asp-route-companyId="@Model.CompanyId"><i class="bi bi-box-arrow-in-right"></i> <span>JOIN</span></a></div>
            </div>
        </div>

    </div>
</div>